### ISSUE TITLE
被包裹的控件，id必须为swipe_target？ 在哪里有说明吗？

### ISSUE THREAD

**Issue by pdog18** [Aspsine/SwipeToLoadLayout#116]
被包裹的控件，id必须为swipe_target？ 在哪里有说明吗？

**Comment by Aspsine** [comment]
https://github.com/Aspsine/SwipeToLoadLayout/wiki/Quick-Setup

> Note:
> refresh header view android:id="@id/swipe_refresh_header"
> target view android:id="@id/swipe_target"
> load more footer view android:id="@id/swipe_load_more_footer"

**Comment by pdog18** [comment]
谢谢您的回复，能否在找不到对应id的时候主动抛出异常呢？
另外想向您请教一下，给控件设置id找到目标子控件，和 getChildAt()有什么区别吗？

**Comment by Aspsine** [comment]
设置id的话，swipetoloadlayout中的child顺序没要求。getChildAt(int)有要求。

**Comment by pdog18** [comment]
嗯谢谢您的回复，您的做法很有道理，
我自己想了一想的确是这样的
不过提一个微小的建议，如果找不到相应的view 还是抛出一个异常来崩溃掉项目吧，昨天因为自己粗心，找了很久才找出原因，（因为自己第一次接触用id去寻找相关控件，经验不足）

谢谢您的项目，很棒，我感觉非常好用，相关api都是非常容易清晰调用的

**Comment by pdog18** [comment]
@Aspsine  请问下您，框架在上拉加载更多的时候，我在使用过程中，数据加载完毕了以后，recyclerview 又回滚至界面底部了，用户使用过程中不能第一时间明确的知道条目被刷新完毕了。
是否有设置可以在上拉加载更多完成时，增加的条目可以直接显示在LoadMore原有的区域呢？

**Comment by Aspsine** [comment]
@pdog18 目前没有。
