### ISSUE TITLE
建议实现 NestedScroll机制

### ISSUE THREAD

**Issue by ysmintor** [Aspsine/SwipeToLoadLayout#117]
https://github.com/hanks-zyh/SwipeRefreshLayout
如同上面对源码的分析一样。
> 下拉刷新控件的主要功能是当子视图下拉到最顶部时，继续下拉可以出现刷新动画。而子视图可以滚动时需要将所有滚动事件都交给子视图。借助 Android 提供的 NestedScrolling 机制，使得 SwipeRefreshLayout 很轻松的解决了与子视图的滚动冲突问题。 SwipeRefreshLayout 通过实现 NestedScrollingParent 和 NestedScrollingChild 接口来处理滚动冲突。

@Aspsine 希望有时间可以实现上述的接口

**Comment by OCTSJimmy** [comment]
强烈希望可以修复这个问题……非常感谢，非常感谢…………

**Comment by ysmintor** [comment]
@OCTSJimmy 现好好像有个SmartRefreshLayout可以支持。
