### ISSUE TITLE
always stop at refreshing

### ISSUE THREAD

**Issue by liunewshine** [Aspsine/SwipeToLoadLayout#24]
![qq 20151122164415](https://cloud.githubusercontent.com/assets/7698511/11322812/6281fd90-9138-11e5-8f5e-85b2b2a6477c.png)
一直停留在这个界面,无法自动回缩
大可乐3,Android 4.4.4

**Comment by Aspsine** [comment]
有可以复现的操作规律呢？

**Comment by liunewshine** [comment]
每次下拉都会出现

**Comment by Aspsine** [comment]
好的，感谢反馈。因为我这边没有机型，可以留个邮箱帮我测试一下么？当然，如果你能找到问题帮祝修复更好。

**Comment by liunewshine** [comment]
好的,liunewshine@qq.com

**Comment by smallgirl** [comment]
Tcl M2m 也是啊

**Comment by hxingever** [comment]
用这个之后页面不能添加其他布局？ 如页面上面固定了一个Linearlayout 下面在添加这个SwipeTOLoadLayout 这种布局的情况下  上面的固定区域会被覆盖看不到了  当然底部固定一个区域也是会被覆盖的

**Comment by Aspsine** [comment]
因为没有相关机型，这个bug始终不是很好定位，希望发现同样问题的童鞋多多反馈。感谢🙏～

**Comment by liutan** [comment]
美图手机也有同样问题

**Comment by liutan** [comment]
onActivePointerUp 时打印状态 显示status_illegal ， 试着将status的类型由byte换成int问题暂时解决，感觉应该是switch时会将括号里的变量自动转换成int导致。 看提交日志之前确为int，不知为何改为byte

**Comment by Aspsine** [comment]
@liutan 感谢你的测试和反馈。1.0.2中马上修复。：）

**Comment by Aspsine** [comment]
@liunewshine 
@smallgirl 
@liutan 

lib和demo都已经更新。
demo下载：
https://raw.githubusercontent.com/Aspsine/SwipeToLoadLayout/master/art/demo.apk
各位测试一下。

**Comment by smallgirl** [comment]
It is ok with Tcl M2m

**Comment by liutan** [comment]
美图也好了
