### ISSUE TITLE
layout issue

### ISSUE THREAD

**Issue by Aspsine** [Aspsine/SwipeToLoadLayout#26]
用这个之后页面不能添加其他布局？ 如页面上面固定了一个Linearlayout 下面在添加这个SwipeTOLoadLayout 这种布局的情况下 上面的固定区域会被覆盖看不到了 当然底部固定一个区域也是会被覆盖的

因为issue类别不一样，删除了你在另外一个issue中的留言。专门开一个issue讨论这个问题。

我测试过，没出现你说的问题。可以麻烦您能把布局文件贴出来么？
@hxingever

**Comment by hxingever** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="?attr/colorBackground"
              android:orientation="vertical"
              tools:context="com.car.cslm.activity.car_lecture_hall.CarLectureCommentsActivty">

    <FrameLayout
        android:id="@+id/fl_container"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

    <LinearLayout
        android:id="@+id/ll_comment"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_alignParentBottom="true"
        android:background="?attr/colorBackground"
        android:orientation="horizontal">

        <EditText
            android:id="@+id/et_comment"
            android:layout_width="0dp"
            android:layout_height="40dp"
            android:layout_gravity="center"
            android:layout_marginLeft="5dp"
            android:layout_weight="1"
            android:background="@drawable/comment_bg"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:hint="说点什么"
            android:inputType="text"
            android:padding="5dp"
            android:textSize="14sp"/>

        <TextView
            android:id="@+id/tv_comment"
            android:layout_width="65dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_marginLeft="8dp"
            android:layout_marginRight="5dp"
            android:background="?attr/colorPrimary"
            android:gravity="center"
            android:padding="@dimen/item_padding"
            android:text="发送"
            android:textColor="?attr/colorTextIcon"/>
    </LinearLayout>
</LinearLayout>

上面FrameLayout里面就是包含的一个fragment(里面只有SwipeToLoadLayout) 静态页面是可以显示下面的布局的或者说上面的数据没有填满时也是可以看见的 但是如果列表数据超过一屏 下面的布局就被挤不见了 本想下面的布局是固定在底部不动的 上两张对比图

![Uploading 列表数据不满一屏.png…]()
![Uploading 列表数据超过一屏.png…]()

**Comment by Aspsine** [comment]
@hxingever 
图片可能没上传成功，但是我大概理解你的意思了。
麻烦，你尝试在把fragment中的SwipeToLoadlayout去掉，只用一个listview，当listview的数据超过一屏看看会不会挤掉下面的布局。

**Comment by hxingever** [comment]
listView是没有问题的  以前用的XlistView也是没有问题的
