### ISSUE TITLE
OnRefresh,OnLoadMore方法多次被调用

### ISSUE THREAD

**Issue by codemonkeyjc** [Aspsine/SwipeToLoadLayout#27]
你好。在Demo里面，onrefresh(),onloadmore()方法会被多次调用的，产生多个网络请求。请问这是不是一个bug？

**Comment by Aspsine** [comment]
感谢反馈，首先肯定一点，如确实存在多次调用onRefresh()和onLoadMore()属于bug。

确定一下：
是我demo中的代码多次调用onRefresh()和onLoadMore()？如果是，麻烦请提供一下重现操作流程，和机型以及系统版本。
如果你能自己能发现问题，解决问题，并pr，那就更好啦～

**Comment by codemonkeyjc** [comment]
不好意思！打扰了。是我的代码有问题，我调用了多次setrefreshing了。这是个非常好用的项目。感谢你的答复。再次对打扰讲一句，不好意思
