### ISSUE TITLE
怎么关闭Log输出？

### ISSUE THREAD

**Issue by lzy26fate** [Aspsine/SwipeToLoadLayout#31]

**Comment by Aspsine** [comment]
https://github.com/Aspsine/SwipeToLoadLayout/blob/master/library/src/main/java/com/aspsine/swipetoloadlayout/SwipeToLoadLayout.java#L1496
```java
private void setStatus(byte status) {
        mStatus = status;
        // STATUS.printStatus(status);
}
```
