### ISSUE TITLE
下拉刷新松开之前向上拽，阻力变小，icon比手更快向上移动了

### ISSUE THREAD

**Issue by limboc** [Aspsine/SwipeToLoadLayout#38]

**Comment by Aspsine** [comment]
see here:
if you want change finger scroll speed, you can modify the method below.
```java
private void fingerScroll(final float yDiff) {}
```
https://github.com/Aspsine/SwipeToLoadLayout/blob/master/library/src/main/java/com/aspsine/swipetoloadlayout/SwipeToLoadLayout.java#L1111
