### ISSUE TITLE
the swipe_target view not show complete

### ISSUE THREAD

**Issue by recwert** [Aspsine/SwipeToLoadLayout#39]
when the swipe_target view is a RelativeLayout who contains the two child view(recyclerview and LinearLayout) , then the recyclerview contains many item, the swipe_target only show one screen
the xml code
`<?xml version="1.0" encoding="utf-8"?>
<com.duoniu.benfu.widget.layout.SwipeToLoadLayoutEmptySupport
    android:id="@+id/swipeToLoadLayout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:swipe_style="classic">

    <include
        android:id="@+id/swipe_refresh_header"
        layout="@layout/layout_logo_header"/>

    <RelativeLayout
        android:id="@id/swipe_target"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.duoniu.benfu.widget.recyclerview.RecyclerViewEmptySupport
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

        </com.duoniu.benfu.widget.recyclerview.RecyclerViewEmptySupport>

        <include layout="@layout/empty_or_error"
            android:id="@+id/emptyView"
            android:visibility="gone"/>
    </RelativeLayout>

    <include
        android:id="@+id/swipe_load_more_footer"
        layout="@layout/layout_classic_footer"/>

</com.duoniu.benfu.widget.layout.SwipeToLoadLayoutEmptySupport>`

how can i solve it?

**Comment by Aspsine** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.aspsine.swipetoloadlayout.SwipeToLoadLayout
        android:id="@+id/swipeToLoadLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:swipe_style="classic">

        <include
            android:id="@+id/swipe_refresh_header"
            layout="@layout/layout_logo_header" />


        <com.duoniu.benfu.widget.recyclerview.RecyclerViewEmptySupport
            android:id="@id/swipe_target"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

        </com.duoniu.benfu.widget.recyclerview.RecyclerViewEmptySupport>


        <include
            android:id="@+id/swipe_load_more_footer"
            layout="@layout/layout_classic_footer" />
    </com.aspsine.swipetoloadlayout.SwipeToLoadLayout>

    <include
        android:id="@+id/emptyView"
        layout="@layout/empty_or_error"
        android:visibility="gone" />
</RelativeLayout>
```
