### ISSUE TITLE
 关于loadmore的一点细节问题

### ISSUE THREAD

**Issue by jyh149129** [Aspsine/SwipeToLoadLayout#42]
当上拉加载完成后，能不能让RecyclerView向上滚动一点距离，让loadmore进来的数据露出一部分，这样能很直观看到数据已经加载进来了，而不是现在必须再手动滚动一次才能看到新数据

**Comment by Aspsine** [comment]
嗯，这也是这个库最大的问题。当时写这个库的时候，出发点在于对所有View一致性的处理方式。忽略了一些体验上的细节问题。
一周内，我会专门针对RecyclerView开源一个下拉刷新，加载更多，以及Header, footer支持的库。这个库会在细节上处理的比较完善。
:) 感谢关注。

**Comment by jyh149129** [comment]
期待，确实不错的库！顺带再问个问题，在adapter设置数据，代码如下：
  public void refreshList(List<News> data,List<FocusPictureNews> lpn,List<View> views) {
        LogUtil.e("size:"+data.size()+",lpn:"+lpn.size()+",views:"+views.size());
        this.lpn.clear();
        this.views.clear();
        this.listItems.clear();
        append(data,lpn,views);
    }


    private void append(List<News> data,List<FocusPictureNews> lpn,List<View> views) {
        this.listItems.addAll(data);
        this.lpn.addAll(lpn);
        this.views.addAll(views);
    }
在方法里和外部activity我并没有调用notifyDataSetChanged（）但也会刷新数据，不知道是不是库在什么地方库已经调用了？

**Comment by Aspsine** [comment]
库中没有针对`AbsListView`或者`RecyclerView`的`Adapter`调用`notifyDataSetChanged()`
`refreshList()`这个方法在哪里调用了？

**Comment by jyh149129** [comment]
在activity调用的，远程取回数据，直接调用refreshList 方法，数据就刷新了。。。我代码里根本没有调用notifyDataSetXXX（）的任何方法。。。

**Comment by Aspsine** [comment]
@jyh149129 
经测试不调用`notifyDataSetChanged();`不会刷新ListView.
