### ISSUE TITLE
锤子手机下拉刷新失败

### ISSUE THREAD

**Issue by androidczc** [Aspsine/SwipeToLoadLayout#44]
锤子手机多次下拉后下拉失效，没有反应。

**Comment by Aspsine** [comment]
@androidczc 
请问用的是demo app么？
不是demo app的话，请贴一下代码。

**Comment by Aspsine** [comment]
[v 1.0.3](https://github.com/Aspsine/SwipeToLoadLayout/releases/tag/1.0.3) is released.
