### ISSUE TITLE
我包裹了自定义的 public class EasyRecyclerView extends FrameLayout出现下面的错误

### ISSUE THREAD

**Issue by ruhaly** [Aspsine/SwipeToLoadLayout#45]
系统异常退出11java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
                                                                    Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
                                                                    android.support.v4.view.ViewCompatICS.canScrollVertically(ViewCompatICS.java:35)
                                                                    android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(ViewCompat.java:1274)
                                                                    android.support.v4.view.ViewCompat.canScrollVertically(ViewCompat.java:1727)
                                                                    com.aspsine.swipetoloadlayout.SwipeToLoadLayout.canChildScrollUp(SwipeToLoadLayout.java:927)
                                                                    com.aspsine.swipetoloadlayout.SwipeToLoadLayout.onCheckCanRefresh(SwipeToLoadLayout.java:897)
                                                                    com.aspsine.swipetoloadlayout.SwipeToLoadLayout.onTouchEvent(SwipeToLoadLayout.java:1060)

**Comment by Aspsine** [comment]
SwipeToLoadLayout对contentView, headerView, footerView的id是有要求的。

请参考step 3来设置正确的id
https://github.com/Aspsine/SwipeToLoadLayout/wiki/Quick-Setup

**Comment by ruhaly** [comment]
系统异常退出11android.view.InflateException: Binary XML file line #14: Error inflating class com.aspsine.swipetoloadlayoutdemo.RefreshHeaderView
                                                                    Binary XML file line #14: Error inflating class com.aspsine.swipetoloadlayoutdemo.RefreshHeaderView




<com.aspsine.swipetoloadlayout.SwipeToLoadLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.aspsine.swipetoloadlayoutdemo.RefreshHeaderView
            android:id="@id/swipe_refresh_header"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:gravity="center" />

        <com.jude.easyrecyclerview.EasyRecyclerView
            android:id="@+id/swipe_target"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />

        <com.aspsine.swipetoloadlayoutdemo.LoadMoreFooterView
            android:id="@id/swipe_load_more_footer"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:gravity="center" />
    </com.aspsine.swipetoloadlayout.SwipeToLoadLayout>

id已经改过来了  但是还是不行

**Comment by Aspsine** [comment]
确定一下：
```
com.aspsine.swipetoloadlayoutdemo.RefreshHeaderView
```
和
```
com.aspsine.swipetoloadlayoutdemo.LoadMoreFooterView
```
是否正确。

这两个view你需要从demo中复制到你的项目中，然后更改为你项目中的路径才可以使用。

**Comment by ycyangchun** [comment]
出现这个问题 ，是不能注解之类的工具 是吗？

**Comment by Aspsine** [comment]
@ycyangchun 
可以使用注解工具。上面的错误和注解工具没有关系。

需要保证：
1. id正确。
2. view路径正确。

**Comment by ycyangchun** [comment]
@Aspsine   问题确实和注解工具无关，我的 listview 自定义了id ，而非是 （swipe_target ）引起异常
