### ISSUE TITLE
下拉刷新头部进度条会不显示

### ISSUE THREAD

**Issue by xubenliang** [Aspsine/SwipeToLoadLayout#47]
这个库感觉挺不错的，但是有些细节可以改进下：
1.如果最外层嵌套的是LinearLayout，下拉刷新头部进度条会不显示。换成RelativeLayout就正常了；
2.ListView的头部与底部的分割线在有HeaderView和FootView的时候是不显示的；
3.加载完成更多，会弹回去，而不是直接显示数据，体验可以改进；
4.主动刷新会先显示下拉即可刷新，然后再显示正在刷新，如果改成直接正在刷新，体验会更好。

**Comment by Aspsine** [comment]
A1.如果最外层嵌套的是LinearLayout，下拉刷新头部进度条会不显示。换成RelativeLayout就正常了；
Q1. 如下布局经测试没发现问题。
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.aspsine.swipetoloadlayout.SwipeToLoadLayout
        android:id="@+id/swipeToLoadLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/style_window_background"
        app:swipe_style="classic"
        tools:context="com.aspsine.swipetoloadlayout.demo.fragment.TwitterListViewFragment">

        <include
            android:id="@id/swipe_refresh_header"
            layout="@layout/layout_twitter_header" />

        <ListView
            android:id="@id/swipe_target"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipToPadding="false"
            android:divider="@null" />

        <include
            android:id="@id/swipe_load_more_footer"
            layout="@layout/layout_classic_footer" />
    </com.aspsine.swipetoloadlayout.SwipeToLoadLayout>
</LinearLayout>
```
Q4.主动刷新会先显示下拉即可刷新，然后再显示正在刷新，如果改成直接正在刷新，体验会更好。
[v 1.0.3]中onMove方法中加入了automatic这个参数。通过判断，可以实现你要的效果。

**Comment by xubenliang** [comment]
Q1.现在这问题又出现，看来不是LinearLayout的原因。目前还不知道具体因为什么。
Q4.很感谢添加这个方法，我试了，很完美。But,又出现了另一个问题。在Tab栏循环切换的时候，调用了setRefreshing(true)方法，但是不执行刷新。在上一个版本是不会这样的。

**Comment by Aspsine** [comment]
>又出现了另一个问题。在Tab栏循环切换的时候，调用了setRefreshing(true)方法，但是不执行刷新。就是刷新完成，弹回去，马上点击切换，这时候没有执行刷新。

请参考https://github.com/Aspsine/SwipeToLoadLayout/wiki/Quick-Setup

```java
private void autoRefresh() {
        swipeToLoadLayout.post(new Runnable() {
            @Override
            public void run() {
                swipeToLoadLayout.setRefreshing(true);
            }
        });
}
```

**Comment by xubenliang** [comment]
我是那样做的，我说的这个问题在上一个版本是不会这样的。目前真不知道为啥进度条有时候会隐藏。

**Comment by xubenliang** [comment]
1.进度条隐藏的问题解决了，我把SwipeRefreshHeaderLayout改成继承RelativeLayout就完美解决了。
2.我的Tab栏点击切换的时候，实际是同一个ListView，没有用到ViewPager和Fragment。

**Comment by xubenliang** [comment]
上个Issues已经关闭，所以写到这里来：
我已经切换到v1.0.3，那个不弹回的问题的确修复好了。
之前用v1.0.3遇到的问题，已经录制了视频：
http://v.youku.com/v_show/id_XMTU2MDM4MDUyMA==.html
开始是点击奖励，然后还在刷新过程中，快速切换到价格，然后就不执行价格的刷新。这个在v1.0.2是不会出现的。
我的Tab栏点击切换的时候，实际是同一个ListView，没有用到ViewPager和Fragment。

**Comment by Aspsine** [comment]
>上个Issues已经关闭，所以写到这里来：
我已经切换到v1.0.3，那个不弹回的问题的确修复好了。
之前用v1.0.3遇到的问题，已经录制了视频：
http://v.youku.com/v_show/id_XMTU2MDM4MDUyMA==.html
开始是点击奖励，然后还在刷新过程中，快速切换到价格，然后就不执行价格的刷新。这个在v1.0.2是不会出现的。
我的Tab栏点击切换的时候，实际是同一个ListView，没有用到ViewPager和Fragment。

```xml
<LinearLayout>

    <LinearLayout>

        <TextView
            android:text="Tab 1" />

        <TextView
            android:text="Tab 2" />
    </LinearLayout>

    <com.aspsine.swipetoloadlayout.SwipeToLoadLayout>
        <HeaderView/>

        <ListView />
    </com.aspsine.swipetoloadlayout.SwipeToLoadLayout>
</LinearLayout>
```
应该这样的结构，点击上面的Tab1 Tab2切换ListView中的数据源对吧？

首先要明确*SwipeToLoadLayout的一个刷新周期是一个完整不可打破的。*

中的Tab1 SwipeToLoadLayout处于刷新ing状态时，你切换到Tab2，要求SwipeToLoadLayout处于Tab2的刷新ing状态。

由于Tab1中的SwipeToLoadLayout和Tab2中的SwipeToLoadLayout是同一个对象，当处于刷新ing状态时，就只能等这个刷新周期完成了才能进行下一次刷新。

建议：
三个Tab用三个不同的SwipeToLoadLayout对象，为了简单期间，建议引入ViewPager。至于用不用Fragment看你。如果不用Fragment，就需要处理好ViewPager切换过程中，View生命周期。

**Comment by xubenliang** [comment]
这个问题在v1.0.2是没有的。我先加个正在刷新，无法切换的判断顶一下，后期有时间按你的建议再改。感谢！！！
