### ISSUE TITLE
It would be great to be able to customise DEFAULT_DRAG_RATIO

### ISSUE THREAD

**Issue by twkx** [Aspsine/SwipeToLoadLayout#48]
It would be very cool for us to have a setDragRatio() method in order to customize the DEFAULT_DRAG_RATIO value.

It would be also great to have a way to customize (DEFAULT_DRAG_RATIO * 4) with another value.

Thanks.

**Comment by Aspsine** [comment]
Good suggestion, maybe next version. 
You can also implement it yourself and give me a pull request. : )

**Comment by Aspsine** [comment]
[v1.0.3](https://github.com/Aspsine/SwipeToLoadLayout/releases/tag/1.0.3) is released.

Now you can set the drag ratio. you can set it in xml or java
- xml
```xml
<com.aspsine.swipetoloadlayout.SwipeToLoadLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipeToLoadLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:drag_ratio="0.5">

```
or 
- java
```java
swipeToLoadLayout.setDragRatio(0.5);
```

**Comment by twkx** [comment]
Thanks a lot fot your amazing fast update !

I’ll use your lib in next release of our app (license included in about section).

Best,

--
Thomas Soulé
Senior Android Developer
News Republic
http://www.news-republic.com

De : Running man! [mailto:notifications@github.com]
Envoyé : dimanche 24 avril 2016 16:27
À : Aspsine/SwipeToLoadLayout <SwipeToLoadLayout@noreply.github.com>
Cc : Thomas SOULE <thomas.soule@news-republic.com>; Author <author@noreply.github.com>
Objet : Re: [Aspsine/SwipeToLoadLayout] It would be great to be able to customise DEFAULT_DRAG_RATIO (#48)


v1.0.3<https://github.com/Aspsine/SwipeToLoadLayout/releases/tag/1.0.3> is released.

Now you can set the drag ratio. you can set it in xml or java

  *   xml

<com.aspsine.swipetoloadlayout.SwipeToLoadLayout xmlns:android="http://schemas.android.com/apk/res/android"

    xmlns:app="http://schemas.android.com/apk/res-auto"

    android:id="@+id/swipeToLoadLayout"

    android:layout_width="match_parent"

    android:layout_height="match_parent"

    app:drag_ratio="0.5">

or

  *   java

swipeToLoadLayout.setDragRatio(0.5);
