### ISSUE TITLE
使用xutils3的injectView注入获取控件，on a null object reference

### ISSUE THREAD

**Issue by Kerwin92** [Aspsine/SwipeToLoadLayout#49]
获取SwipeToLoadLayout的内部及自身控件，比如com.aspsine.swipetoloadlayout.SwipeToLoadLayout，RecyclerView等都会null

**Comment by Aspsine** [comment]
you must use specified ids
please look over step 3 in the link below
https://github.com/Aspsine/SwipeToLoadLayout/wiki/Quick-Setup

```xml
<?xml version="1.0" encoding="utf-8"?>
<com.aspsine.swipetoloadlayout.SwipeToLoadLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/swipeToLoadLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.aspsine.swipetoloadlayoutdemo.MainActivity">

    <com.aspsine.swipetoloadlayoutdemo.RefreshHeaderView
        android:id="@id/swipe_refresh_header"
        android:layout_width="match_parent"
        android:gravity="center"
        android:layout_height="100dp" />

    <ListView
        android:id="@id/swipe_target"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <com.aspsine.swipetoloadlayoutdemo.LoadMoreFooterView
        android:id="@id/swipe_load_more_footer"
        android:layout_width="match_parent"
        android:gravity="center"
        android:layout_height="100dp" />

</com.aspsine.swipetoloadlayout.SwipeToLoadLayout>
```
- refresh header view
`android:id="@id/swipe_refresh_header"`

- target view
`android:id="@id/swipe_target"`

- load more footer view
`android:id="@id/swipe_load_more_footer"`

**Comment by Kerwin92** [comment]
@Aspsine thanks ,you are really appreciated 
I have seen [#45](https://github.com/Aspsine/SwipeToLoadLayout/issues/45) and checked my SwipeToLoadLayout and RefreshHeaderView ,I just copied the code from sample.
They run right with "findviewbyid" ,but "on a null object reference" when used with xUtils 
`
@ViewInject(R.id.swipeToLoadLayout)
`

**Comment by Aspsine** [comment]
It's maybe a bug of XUtils. I'm not sure.

**Comment by Kerwin92** [comment]
@Aspsine 
ok tks

**Comment by brucezz** [comment]
@Aspsine  Please highlight these view ids in [Quick-Setup](https://github.com/Aspsine/SwipeToLoadLayout/wiki/Quick-Setup).

refresh header view
`android:id="@id/swipe_refresh_header"`
target view
`android:id="@id/swipe_target"`
load more footer view
`android:id="@id/swipe_load_more_footer"`

**Comment by Aspsine** [comment]
@brucezz Added.

**Comment by brucezz** [comment]
@Aspsine  Thanks for your nice library 😄
