### ISSUE TITLE
不支持ScrollView

### ISSUE THREAD

**Issue by tsunamilx** [Aspsine/SwipeToLoadLayout#55]
Hi
我有一个很长的详情页，所以用了ScrollView，然后在底部有个评论列表，我用了你的这个layout，然后发现是空白的，我去掉了ScrollView，保留少量内容，可以看到你的layout可以正常工作，加上ScrollView，你的layout又空白了，我固定了你的layout的高度，看到里面有内容的，所以估计是高度被错误算成了0。

请问像我这样情况有没有办法？

**Comment by Aspsine** [comment]
贴一下布局xml。

**Comment by tsunamilx** [comment]
就是基本的layout
```xml
<ScrollView>
  <LinearLayout>
   
   N 多个View

     <你的layout>
     </你的layout>

  </LinearLayout>
</ScrollView>
```
完整的xml在这里：
[scrollview.txt](https://github.com/Aspsine/SwipeToLoadLayout/files/248556/scrollview.txt)

**Comment by Aspsine** [comment]
@tsunamilx 
不支持你这样用。

请改为如下格式。
```xml
<SwipeToLoadLayout>
    <HeaderView/>

    <ScrollView>

      <LinearLayout>
      </LinearLayout>

    </ScrollView>

    <FooterView/>
</SwipeToLoadLayout>
```

**Comment by tsunamilx** [comment]
高手就是高手！ 👍

**Comment by KimRasak** [comment]
> @tsunamilx
> 不支持你这样用。
> 
> 请改为如下格式。
> 
> ```
> <SwipeToLoadLayout>
>     <HeaderView/>
> 
>     <ScrollView>
> 
>       <LinearLayout>
>       </LinearLayout>
> 
>     </ScrollView>
> 
>     <FooterView/>
> </SwipeToLoadLayout>
> ```

上述操作有效。如此，应当标注为```android:id="swipe_target"```的是```<ScrollView>```，不要标错到```<LinearLayout>```内的某个标签上了。
