### ISSUE TITLE
 The content of the adapter has changed but ListView did not receive a notification

### ISSUE THREAD

**Issue by xubenliang** [Aspsine/SwipeToLoadLayout#58]
使用ViewPager+Fragment，SwipeToLoadLayout还没刷新完成，就快速切换到其它页面，很容易出现以下错误：
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558425, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]

之前有说这样解决：
崩溃问题是更新了数据源之后没有调用notifyDataSetChanged()。比如如下使用方式就可能出现崩溃。

onSuccess(data){
  mList.addAll(data);
  swipeToLoadLayout.setRefreshing(false);
  mAdapter.notifyDataSetChanged();
}
按照上面这样的用法，就会出现如上崩溃。
请修改为：

onSuccess(data){
  swipeToLoadLayout.setRefreshing(false);
  mList.addAll(data);
  mAdapter.notifyDataSetChanged();
}

我是那么做的，但是还是不行。

**Comment by Aspsine** [comment]
首先明确一点这个Exception是ListView抛出的，和SwipeToLoadLayout没关系。

这个错误的message已经描述的很清楚了:
```
The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. 
```
翻译过来就是
```
Adapter内容改变后，ListView没有收到通知。要保证adapter的内容只能在主线程进行修改，不能在子线程中修改。确保一旦adapter内容有改变就要调用notifyDataSetChanged()方法。
```
请根据错误提示对代码进行检查。

**Comment by xubenliang** [comment]
换RecycleView问题解决。
