### ISSUE TITLE
加载更多完成后

### ISSUE THREAD

**Issue by niq2003** [Aspsine/SwipeToLoadLayout#59]
目前当加载更多完成后，footer消失，列表回弹footer的高度，到底部，加载的内容不能立即显示，能否实现列表不动，footer消失，加载的内容显示在footer的位置？

**Comment by Aspsine** [comment]
从SwipeToLoadLayout层面做不到你说的效果。

可以看看
https://github.com/Aspsine/IRecyclerView
是否满足你的需求。
