### ISSUE TITLE
SwipeToLoadLayout  布局只能是layout根布局吗？

### ISSUE THREAD

**Issue by ycyangchun** [Aspsine/SwipeToLoadLayout#60]
可不可以
<RelativeLayout >
<com.aspsine.swipetoloadlayout.SwipeToLoadLayout  />
</RelativeLayout >

**Comment by Aspsine** [comment]
对是否根布局没有做限制，都可以。

**Comment by ycyangchun** [comment]
使用了butterknife  应该是这个引起的
