### ISSUE TITLE
请问如何在adapter加载不同item布局，如何传递数据

### ISSUE THREAD

**Issue by houde0820** [Aspsine/SwipeToLoadLayout#62]

**Comment by TakWolf** [comment]
adapter中加载不同数据，这个是ListView或者RecyclerView的使用问题，更该项目的下拉刷新没关系。

加载不同item的方法：

如果是RecyclerView，Adapter中重写方法：

`getItemViewType`

在`onCreateViewHolder`中根据不同的viewType创建不同的viewHolder

如果是ListView, 重写如下方法：

```
    @Override
    public int getItemViewType(int position) {
    }

    @Override
    public int getViewTypeCount() {
    }
```
在getView中根据不同的viewType创建不同的布局

**Comment by TakWolf** [comment]
关于数据传递，不清楚你指的是什么情况。

adapter实际过程中一定依赖一个数据源
对数据源更新之后，通过`adapter.notifyDataSetChanged();`,就能够保证列表是更新的

**Comment by Aspsine** [comment]
@houde0820
首先感谢@TakWolf ，关于adapter对不同布局的加载，已经说明的很清楚。

抱歉我要关闭这个issue，因为这个问题不属于这个项目的issue。

首先要善用搜索引擎。其次如果有不能解决的问题请到专业的问题社区http://stackoverflow.com 进行提问。
