### ISSUE TITLE
setSwipeStyle()

### ISSUE THREAD

**Issue by shichunlei** [Aspsine/SwipeToLoadLayout#67]
可不可以分别设置头部与底部的STYLE；

比如头部的样式为STYLE.ABOV，而底部的样式为STYLE.SCALE

或者，同时存在整体STYLE、头部STYLE、底部STYLE。

试着改了一下源码，没有成功，因为设置中间部分的STYLE，这部分不知道该怎么设置它的STYLE。

**Comment by Aspsine** [comment]
不可以分别设置头部和底部的style.

目前的'setSwipeStyle(int)'方法同时控制header和footer的style。

当时考虑过分别设置style，不过layout逻辑就比较复杂。因为header 4种style，footer 4种style，一共有16种组合。

如果你有这样的需求，可以通过修改`layoutChildren()`来实现。

**Comment by shichunlei** [comment]
好的，我试试
