### ISSUE TITLE
你好 1.0.3 通过gradle 依赖 弄不下来

### ISSUE THREAD

**Issue by vipheyue** [Aspsine/SwipeToLoadLayout#72]
![1b6a8f93-0a57-44ef-a9e3-923be53749bb](https://cloud.githubusercontent.com/assets/11717882/17393608/5b15024e-5a57-11e6-9567-f575cfb8a3b7.png)

**Comment by vipheyue** [comment]
1.0.2可以

**Comment by Carpten** [comment]
我也是

**Comment by fableyjg** [comment]
Step 1. Add the JitPack repository in your build.gradle at the end of repositories:
repositories {
    maven { url "https://jitpack.io" }
}
首先添加这个，就ok了。

**Comment by Aspsine** [comment]
https://github.com/Aspsine/SwipeToLoadLayout/wiki/Dependency

**Comment by vipheyue** [comment]
compile 'com.github.Aspsine:SwipeToLoadLayout:v1.0.3'
    compile 'com.github.Aspsine:SwipeToLoadLayout:1.0.3'
 #知道了,,没有v......

**Comment by Aspsine** [comment]
@vipheyue 谢谢，我也疏忽了。

**Comment by Carpten** [comment]
我也解决了，我把
repositories {
maven { url "https://jitpack.io" }
}
加在buildscript的repositories 标签了
