### ISSUE TITLE
拷贝项目

### ISSUE THREAD

**Issue by caoanqi** [Aspsine/SwipeToLoadLayout#76]
你好
      是这样的，我把你项目里的libary  拷贝到我的项目类库中，但是却在layout 文件 引用不到？
感谢！

**Comment by Aspsine** [comment]
你寻找的layout可能不在library module项目中，在app module中。

**Comment by caoanqi** [comment]
我把library 中的文件 拷贝到 已经存在的类库项目中 ，是可以找到，不明白什么原因 ，也只能暂时先不管他了。
感谢！
