### ISSUE TITLE
和RecyclerView一起使用碰到的问题

### ISSUE THREAD

**Issue by sakurajiang** [Aspsine/SwipeToLoadLayout#77]
我自定义了刷新和加载的样式，但是不会显示出来，刷新和加载能成功，就是没有显示我自己的样式，我自定义的样式是继承TextView，我的RecyclerView的item中没有TextView，请问是这个原因吗？

**Comment by Aspsine** [comment]
如果header和footer都是简单的TextView, 看这里
https://github.com/Aspsine/SwipeToLoadLayout/wiki/Quick-Setup

**Comment by sakurajiang** [comment]
这里listView中的item页面里有TextView吗？我的意思是刷新的头部和尾部继承一个TextView，它的显示与否和item页面是否有TextView有关吗？

**Comment by Aspsine** [comment]
@sakurajiang refresh header和load more footer中有什么view和item中有什么view互不干涉。
