### ISSUE TITLE
你好，我有个疑问

### ISSUE THREAD

**Issue by sakurajiang** [Aspsine/SwipeToLoadLayout#81]
你好，我有个疑问，我在自定义刷新头部的时候，实现 SwipeRefreshTrigger, SwipeTrigger这两个接口后，复写的那些方法是什么意思，比如onComplete()，是指刷新的时候请求数据完成的时候调用还是指什么？谢谢！

**Comment by Aspsine** [comment]
SwipeRefreshTrigger 与SwipeTrigger 都是对下拉刷新过程中的状态回调。

在 SwipeToLoadLayout 的 demo 中，用它们主要去控制 header view 中的状态。
