### ISSUE TITLE
dispatchTouchEvent

### ISSUE THREAD

**Issue by shanmudashuty** [Aspsine/SwipeToLoadLayout#82]
// swipeToRefresh -> finger up -> finger down if the status is still swipeToRefresh
// in onInterceptTouchEvent ACTION_DOWN event will stop the scroller
// if the event pass to the child view while ACTION_MOVE(condition is false)
// in onInterceptTouchEvent ACTION_MOVE the ACTION_UP or ACTION_CANCEL will not be
// passed to onInterceptTouchEvent and onTouchEvent. Instead It will be passed to
// child view's onTouchEvent. So we must deal this situation in dispatchTouchEvent

这个是啥意思？能用中文描述下吗？

**Comment by Aspsine** [comment]
这是我当时为了解决一个bug写的一段chenglish，见笑了。

当前状态是`SWIPING_TO_REFRESH`的时候，抬起手指，然后落下手指。如果这时候状态依然是`SWIPEING_TO_REFRESH`(当速度特别快的时候，header没有收缩到原位，所以这种情况是可能的。)

当时`onInterceptTouchEvent` ACTION_DOWN中是这样的：
```java
if (!(STATUS.isRefreshComplete(mStatus) || STATUS.isLoadMoreComplete(mStatus))
                        && !(STATUS.isRefreshing(mStatus) || STATUS.isLoadingMore(mStatus))) {
mAutoScroller.abortIfRunning();
}
```

这时候明显if条件是成立的，所以
```java
mAutoScroller.abortIfRunning();
```
会执行，让scroller停止。

这时候手指如果移动，在`ACTION_MOVE `中的tiriggerCondition为false。

```java
boolean triggerCondition = (yInitDiff > 0 && moved && onCheckCanRefresh())
                        || (yInitDiff < 0 && moved && onCheckCanLoadMore());
if (triggerCondition) {
                    // the trigger condition refresh or load more is true
                    // intercept the move action event and pass it to SwipeToLoadLayout#onTouchEvent()
                    return true;
                }
```

这次事件就不能拦截在SwipeToLoadLayout中，而是会传向swipe_tagert这id的子view的`onTouchEevent`。所以随后的ACTION_UP和ACTION_CANCEL都不会传向`onInterceptTouchEvent`和`onTouchEvent`。

而我在SwipeToLoadLayout的`onTouchEvent的`ACTION_UP`和`ACTION_CANCEL`中调用了`onActivePointerUp()`来让scroller运行，让header弹回去。
```
case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_CANCEL:
                if (mActivePointerId == INVALID_POINTER) {
                    return false;
                }
                onActivePointerUp();
                mActivePointerId = INVALID_POINTER;
                break;
```

所以，就导致了当时header会卡住的bug。

然后当时的处理方式是，把｀ onActivePointerUp()`放在`dispatchTouchEvent `中去执行。bug就fix了。

当时处理这个问题用的时间比较长，然后就做了一下简单的记录。

从现在的代码里面应该是找不到轨迹了。

看这里：
https://github.com/Aspsine/SwipeToLoadLayout/blob/45a3fda1c6092afb621049a77e2241c5d26f90bb/library/src/main/java/com/aspsine/swipetoloadlayout/SwipeToLoadLayout.java#L932
