### ISSUE TITLE
在fragment里面套用RecyclerView数据不显示

### ISSUE THREAD

**Issue by zengcanxiang** [Aspsine/SwipeToLoadLayout#90]
很是奇怪，我在两个fragment里面使用，然后一个可以显示列表加载的数据，一个不显示，更不用说下拉了。
他们之间的区别就是一个布局就只有SwipeToLoadLayout,一个除了SwipeToLoadLayout之外还有很多,并且是通过权重来布局的。但是删除SwipeToLoadLayout就可以显示. 
我怕是我没写好，在同级下，新增了一个fragment的(就是很常见的4个fragment切换,是通过hide和show).
发现本来第一个是显示的，切换到第2个不显示，然后切换回第一个，原来的adapter不显示了，显示了第2个的adapter.
于是，我就测试，把第一个界面的代码全部隐藏，购物车布局和代码没有做任何修改。然后就可以显示了.
是我使用的时候，哪里不对么？
还是因为swipe_target这种设置不能这样写呢？或者是需要进行什么处理？
因为我阅读demo的时候，都是viewpager+fragment。不是同级的fragment通过hide和show切换

**Comment by zengcanxiang** [comment]
![qq 20161114104059](https://cloud.githubusercontent.com/assets/16033497/20251958/d7475104-aa58-11e6-80b9-f71ec7e631ee.png)
![qq 20161114105106](https://cloud.githubusercontent.com/assets/16033497/20251959/d76ada98-aa58-11e6-8ebc-a5ba752259fe.png)

**Comment by zengcanxiang** [comment]
我将首页的fragment切换成了viewpager的形式来显示，发现还是不行.但是只要swipe_target不同时存在两个，那么久不会存在这个问题。请问应该怎么解决.因为不使用swipe_target好像是不行的.

**Comment by zengcanxiang** [comment]
我下载源码，将swipe_target这个写死的配置到attrs文件中，然后增加了一个属性值来获取.这样就可以了。是不是应该将这个写死的id给放开呢？ : )

```java
 else if (attr == R.styleable.SwipeToLoadLayout_target_id) {
          targetId = a.getResourceId(attr, R.id.swipe_target);
 }

 @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        final int childNum = getChildCount();
        if (childNum == 0) {
            // no child return
            return;
        } else if (0 < childNum && childNum < 4) {
            mHeaderView = findViewById(R.id.swipe_refresh_header);
            mTargetView = findViewById(targetId);
            mFooterView = findViewById(R.id.swipe_load_more_footer);
        } else {
            // more than three children: unsupported!
            throw new IllegalStateException("Children num must equal or less than 3");
        }
        if (mTargetView == null) {
            return;
        }
        if (mHeaderView != null && mHeaderView instanceof SwipeTrigger) {
            mHeaderView.setVisibility(GONE);
        }
        if (mFooterView != null && mFooterView instanceof SwipeTrigger) {
            mFooterView.setVisibility(GONE);
        }
    }
```

**Comment by zengcanxiang** [comment]
但是我发现，我这个一个fragment设置的刷新，会让另一个fragment里面的swipeToLoadLayout触发，本身的却是触发不了下拉事件.
而且两边的数据都已经显示了，mTargetView也不一样

**Comment by Aspsine** [comment]
Q1:
>在同级下，新增了一个fragment的(就是很常见的4个fragment切换,是通过hide和show).
发现本来第一个是显示的，切换到第2个不显示，然后切换回第一个，原来的adapter不显示了，显示了第2         个的adapter.

A1:
SwipeToLoadLayout就是一个自定义的viewgroup，本身不会影响不同fragment的切换。不同fragment中的SwipeToLoadLayout请保持不同的实例。
看你的描述，导致这种问题的有两种可能：
1. Fragment 错乱。
2.四个Tab Fragment 持有的SwipeToLoadLayout是同一个实例。

Q2:
>下载源码，将swipe_target这个写死的配置到attrs文件中，然后增加了一个属性值来获取.这样就可以显示数据了.

A2:
思路很好，可以这样修改。


Q3：
>一个fragment设置的刷新，会让另一个fragment里面的swipeToLoadLayout触发，本身的却是触发不了下拉事件`

A3:
大兄弟，我可以肯定你不同fragment中的SwipeToLoadLayout是同一个view实例。：）

**Comment by zengcanxiang** [comment]
@Aspsine 怎么导致是一个view实例呢，在不同的fragment里面吖,能指点一下么

**Comment by zengcanxiang** [comment]
我的天啊，明白了，我在封装baseFragment的时候，抽离了一个findViewById()的方法，以前手写都是使用view.find，封装的时候，手顺，写成了getActivity()。。。。。
