### ISSUE TITLE
您好，我又来了。

### ISSUE THREAD

**Issue by gaohequan** [Aspsine/SwipeToLoadLayout#95]
有个建议的小优化，当给recyclerView添加点击事件的时候，点击事件和下拉或者上啦事件有冲突。虽然不是很大的问题，但是偶尔体验不好。可不可以加一个上下滑动的距离，超过这个距离才会触发上啦或者下拉的事件。不知道我这样描述您清楚么？

**Comment by Aspsine** [comment]
Fixed.
